### ISSUE TITLE
TypeError - can't convert Fixnum to String

### ISSUE THREAD

**Issue by linko** [DavyJonesLocker/client_side_validations#526]
I got this error here 

https://github.com/bcardarella/client_side_validations/blob/3-2-stable/lib/client_side_validations/action_view/form_builder.rb#L98

``` ruby
child_index = @options[:child_index] ? "(\\d+|#{Regexp.escape(@options[:child_index])})" : "\\d+"
```

with the @options[:child_index] value equal to 70250948893180 (added debug output into gem file)

if I just add .to_s like this

``` ruby
child_index = @options[:child_index] ? "(\\d+|#{Regexp.escape(@options[:child_index].to_s)})" : "\\d+" 
```

the problem is solved. What is a best solution for this? Or can I force cast .to_s on that option?

Here is a trace:

``` code
  (gem) client_side_validations-3.2.5/lib/client_side_validations/action_view/form_builder.rb:99:in `escape'
  (gem) client_side_validations-3.2.5/lib/client_side_validations/action_view/form_builder.rb:99:in `build_validation_options'
  (gem) client_side_validations-3.2.5/lib/client_side_validations/action_view/form_builder.rb:75:in `collection_select_with_client_side_validations'
  (gem) simple_form-2.0.4/lib/simple_form/inputs/collection_select_input.rb:7:in `input'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/many.rb:29:in `block in render'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/many.rb:27:in `each'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/many.rb:27:in `render'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/many.rb:29:in `block in render'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/many.rb:27:in `each'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/many.rb:27:in `render'
  (gem) simple_form-2.0.4/lib/simple_form/wrappers/root.rb:15:in `render'
  (gem) simple_form-2.0.4/lib/simple_form/form_builder.rb:116:in `input'
  (gem) client_side_validations-simple_form-2.0.1/lib/client_side_validations/simple_form/form_builder.rb:29:in `input_with_client_side_validations'
 app/views/application/_medium_classification.html.haml:2:in `_app_views_application__medium_classification_html_haml__1927438638199952841_70250948595540'

```

The code which raises this error.

``` ruby
= f.simple_fields_for :medium_classifications, validate: false do |builder|
  = render 'medium_classification', f: builder 
```

and **_medium_classification.rb** below

``` ruby
.sub
  - collection = @products || []
  = f.input :product_id, collection: collection.collect{|x| [x.title.gsub('&nbsp;', ' '), x.id]}, label: false, prompt: 'Select One or More'
  = link_to_remove_fields("Remove", f)
```

Gemfile 

``` ruby
simple_form (2.0.4)
client_side_validations (3.2.5)
client_side_validations-simple_form(2.0.1)
```

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
