### ISSUE TITLE
Wrong number of arguments with v 3.2.7

### ISSUE THREAD

**Issue by dhampik** [DavyJonesLocker/client_side_validations#613]
Previously was using the following version of the gem with Rails 4.2:
~~~ruby
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: '4-2-stable'
~~~
And it was working fine, no issues
Then I saw, that new version released, so I updated to:
~~~ruby
gem 'client_side_validations', '3.2.7'
~~~
And got a lot of errors in my tests like this one:
~~~
ActionView::Template::Error:
       wrong number of arguments (3 for 2)
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/client_side_validations-3.2.7/lib/client_side_validations/action_view/form_helper.rb:48:in `apply_form_for_options!'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/helpers/form_helper.rb:434:in `form_for'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/client_side_validations-3.2.7/lib/client_side_validations/action_view/form_helper.rb:25:in `form_for'
     # ./app/views/filtered/_form.html.erb:1:in `_app_views_filtered__form_html_erb___767674494260131336_14799940'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/template.rb:333:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/template.rb:143:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:47:in `render_partial'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:21:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
     # ./app/views/filtered/new.html.erb:4:in `_app_views_filtered_new_html_erb__2086841296791351462_19908140'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/template.rb:333:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/template.rb:143:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:23:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/rendering.rb:100:in `_render_template'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/rendering.rb:83:in `render_to_body'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/abstract_controller/rendering.rb:25:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:16:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
     # ./app/controllers/filtered_controller.rb:56:in `new'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:632:in `process'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:65:in `process'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `block in process'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `catch'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `process'
     # /home/dhampik/.rvm/gems/ruby-2.1.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:508:in `get'
     # ./spec/controllers/filtered_controller_spec.rb:29:in `block (3 levels) in <top (required)>'
~~~

Is there some breaking change in past release or master is still not ready for rails 4.2?

BTW, thanks for your efforts on keeping this gem updated!

**Comment by tagliala** [comment]
@dhampik ffff I missed the chance to properly set dependencies in the 3.2 stable branch.

I just want to confirm that the 3.2 branch is unmantained and will be unmantained.

As per README: https://github.com/DavyJonesLocker/client_side_validations#versioning I want to confirm that version 3.2.7 will not work with Rails > 3.2. Please keep using the master branch

I had to release 3.2.7, but the 4.2.0 version will not see the light soon because there are still things to do.

Hope it helps, closing here

Dup of #603

**Comment by dhampik** [comment]
Thanks for info, @tagliala!
