### ISSUE TITLE
Java script error while validating numericality: greater_than with other model attribute

### ISSUE THREAD

**Issue by varvaray** [DavyJonesLocker/client_side_validations#679]
I have 2 attributes in my model - minimum_players and maximum_players. And i want compare them in validation:
```rb
 validates :maximum_players, presence: true, numericality: { only_integer: true, greater_than: :minimum_players }

validates :minimum_players, presence: true, numericality: { only_integer: true, less_than: :maximum_players }
```
The thing is, if in my form i'll erase the value, i'll get an error  - 
```
VM9416:3 Uncaught SyntaxError: Unexpected token }
    at new Function (<anonymous>)
    at Object.numericality (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:57073:18)
    at executeValidators (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:56808:30)
    at validateElement (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:56833:9)
    at jQuery.fn.init.$.fn.isValid (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:56750:14)
    at HTMLInputElement.<anonymous> (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:57884:40)
    at HTMLInputElement.dispatch (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:5227:27)
    at HTMLInputElement.elemData.handle (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:4879:28)
    at Object.trigger (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:5131:12)
    at Object.simulate (http://localhost:3000/assets/application-bb85fcb8fe8ac097e6f76a98bc2fa968ac9dc1d5a76c575d837a260aa4181540.js:5485:16)
```

So, i was wondering if adding the null-check on line 369

```js
if (check_value) {
     fn = new Function("return " + val + " " + operator + " " + check_value);
       if (!fn()) {
           return options.messages[check];
      }
  }
```

like that can be done to fix that behaviour?

**Comment by tagliala** [comment]
Sorry for the late reply, I can confirm there is an issue.

I'm investigating

**Comment by tagliala** [comment]
@varvaray could you please give the master branch a try?

```rb
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
```

**Comment by varvaray** [comment]
@tagliala thank you, work perfectly now! =)

**Comment by varvaray** [comment]
@tagliala I actually have a comment here. If i remove 1 of the fields, it doesn't show any messages anymore, but when i try to submit, i'm getting server validation fail. I suppose it's better to reproduce server side behaviour, what do you think?

    validates :maximum_players,
              allow_nil: true,
              numericality: { only_integer: true, less_than_or_equal_to: 2147483647, greater_than_or_equal_to: :minimum_players }

    validates :minimum_players,
              allow_nil: true,
              numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: :maximum_players }

<img width="658" alt="screen shot 2016-12-09 at 17 39 53" src="https://cloud.githubusercontent.com/assets/2878034/21054457/8565d634-be36-11e6-8020-e983915200e4.png">

**Comment by tagliala** [comment]
@varvaray please open a new issue and copy & paste your message
